eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - TokenRelay=
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/ander
        registration:
          keycloak:
            provider: keycloak
            client-id: ander-app
            client-secret: PDf11JNKVejkXLTR1rq8ffnZWL1bZIzV
            authorization-grant-type: authorization_code
            scope: openid

server:
  port: 8081
