spring:
  application:
    name: resource
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8071

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
