server:
  port: 8761

spring:
  application:
    name: eureka-server
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8071

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
